[package]
name = "ultralight"
version = "0.1.1"
edition = "2021"
description = "Rust bindings for Ultralight. Next-Generation HTML Renderer"
homepage = "https://ultralig.ht/"
license-file = "LICENSE"

[dependencies]
image = "0.24.0"

[build-dependencies]
bindgen = "0.68.0"