[package]
name = "ultralight"
version = "0.1.0"
edition = "2021"
description = "Rust bindings for Ultralight. Next-Generation HTML Renderer"
homepage = "https://ultralig.ht/"
license-file = "LICENSE"

[dependencies]
image = "*"

[build-dependencies]
bindgen = "0.68.0"